# Generated by Django 5.1.7 on 2025-05-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_rename_first_name_passenger_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="name",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="surname",
        ),
    ]
